[package]
name = "cycle"
version = "0.0.2"
description = "Mathematical modeling using symbolic trees"
authors = ["hrkz <hugo.frezat@gmail.com>"]

keywords = ["symbolic", "mathematics", "modeling", "analysis"]
edition = "2018"
license = "MIT"
readme = "README.md"

homepage = "https://cycle-research.org"
repository = "https://github.com/hrkz/cycle/"

[dependencies]

[[bin]]
name = "main"
path = "bin/main.rs"
doc = false

[workspace]
members = [
  "cycle-eval",
  "cycle-num"
]
