[package]
name = "cycle-stats"
version = "0.0.1"
description = "statistics package for cycle"
authors = ["hrkz <hugo.frezat@gmail.com>"]

edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
cycle = { path = "../../" }
