on: [push, pull_request]

name: CI

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        toolchain:
          - nightly

    steps:
      - uses: actions/checkout@v2

      - name: Installing
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
          components: rustfmt

      - name: Building
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace

      - name: Testing
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace

      - name: Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
